return function(dragonhub)
    dragonhub:AddTheme({
        Name = "DragonHub (New Year)",
        Accent = Color3.fromHex("#33CCFF"),
        Background = Color3.fromHex("#121A2E"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#A0E8FF"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#C0D8F0"),
        Button = Color3.fromHex("#2B8FFF"),
        Icon = Color3.fromHex("#B0E0FF"),
        Hover = Color3.fromHex("#66D9FF"),
        WindowBackground = Color3.fromHex("#121A2E"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#182544"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#E6F9FF"),
        DialogIcon = Color3.fromHex("#B0E0FF"),
        WindowTopbarButtonIcon = Color3.fromHex("#B0E0FF"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#C8EEFF"),
        WindowTopbarIcon = Color3.fromHex("#33CCFF"),
        TabBackground = Color3.fromHex("#1A294A"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#87CEEB"),
        ElementBackground = Color3.fromHex("#1F3155"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#C0D8F0"),
        ElementIcon = Color3.fromHex("#87CEEB"),
        PopupBackground = Color3.fromHex("#182544"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#E6F9FF"),
        PopupIcon = Color3.fromHex("#B0E0FF")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (Fire Dragon)",
        Accent = Color3.fromHex("#FF6A00"),
        Background = Color3.fromHex("#140600"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#FF8C1A"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#FFB366"),
        Button = Color3.fromHex("#CC3300"),
        Icon = Color3.fromHex("#FF7B00"),
        Hover = Color3.fromHex("#FF4500"),
        WindowBackground = Color3.fromHex("#140600"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#241000"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#FFD9B3"),
        DialogIcon = Color3.fromHex("#FF7B00"),
        WindowTopbarButtonIcon = Color3.fromHex("#FF8C1A"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#FFB366"),
        WindowTopbarIcon = Color3.fromHex("#FF6A00"),
        TabBackground = Color3.fromHex("#2B1200"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#FF8C1A"),
        ElementBackground = Color3.fromHex("#331400"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#FFB366"),
        ElementIcon = Color3.fromHex("#FF7B00"),
        PopupBackground = Color3.fromHex("#241000"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#FFD9B3"),
        PopupIcon = Color3.fromHex("#FF7B00")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (Dark Sakura)",
        Accent = Color3.fromHex("#E78FB3"),
        Background = Color3.fromHex("#120E14"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#F2B6CF"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#DDBFD0"),
        Button = Color3.fromHex("#C85A8E"),
        Icon = Color3.fromHex("#F2B6CF"),
        Hover = Color3.fromHex("#F4A6C1"),
        WindowBackground = Color3.fromHex("#120E14"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#1C1621"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#F8EAF1"),
        DialogIcon = Color3.fromHex("#F2B6CF"),
        WindowTopbarButtonIcon = Color3.fromHex("#F2B6CF"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#DDBFD0"),
        WindowTopbarIcon = Color3.fromHex("#E78FB3"),
        TabBackground = Color3.fromHex("#241B2A"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#F2B6CF"),
        ElementBackground = Color3.fromHex("#2D2333"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#DDBFD0"),
        ElementIcon = Color3.fromHex("#F2B6CF"),
        PopupBackground = Color3.fromHex("#1C1621"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#F8EAF1"),
        PopupIcon = Color3.fromHex("#F2B6CF")
    })
    
    dragonhub:AddTheme({
        Name = "DragonHub (Lavender Dream)",
        Accent = Color3.fromHex("#B794F4"),
        Background = Color3.fromHex("#10101A"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#D6BCFA"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#D9C8F8"),
        Button = Color3.fromHex("#8B5CF6"),
        Icon = Color3.fromHex("#D6BCFA"),
        Hover = Color3.fromHex("#C4A7FF"),
        WindowBackground = Color3.fromHex("#10101A"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#191925"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#F2ECFF"),
        DialogIcon = Color3.fromHex("#D6BCFA"),
        WindowTopbarButtonIcon = Color3.fromHex("#D6BCFA"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#D9C8F8"),
        WindowTopbarIcon = Color3.fromHex("#B794F4"),
        TabBackground = Color3.fromHex("#232338"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#D6BCFA"),
        ElementBackground = Color3.fromHex("#2C2C45"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#D9C8F8"),
        ElementIcon = Color3.fromHex("#D6BCFA"),
        PopupBackground = Color3.fromHex("#191925"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#F2ECFF"),
        PopupIcon = Color3.fromHex("#D6BCFA")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (Purple Nebula)",
        Accent = Color3.fromHex("#C26DFF"),
        Background = Color3.fromHex("#0D0619"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#E040FB"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#D896FF"),
        Button = Color3.fromHex("#9C27B0"),
        Icon = Color3.fromHex("#E040FB"),
        Hover = Color3.fromHex("#E040FB"),
        WindowBackground = Color3.fromHex("#0D0619"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#1A0A2E"),
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#E6E6FA"),
        DialogIcon = Color3.fromHex("#E040FB"),
        WindowTopbarButtonIcon = Color3.fromHex("#E040FB"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#D896FF"),
        WindowTopbarIcon = Color3.fromHex("#C26DFF"),
        TabBackground = Color3.fromHex("#16213E"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#BA68C8"),
        ElementBackground = Color3.fromHex("#1E1533"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#D896FF"),
        ElementIcon = Color3.fromHex("#E040FB"),
        PopupBackground = Color3.fromHex("#1A0A2E"),
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#E6E6FA"),
        PopupIcon = Color3.fromHex("#E040FB")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (Emerald Toxic)",
        Accent = Color3.fromHex("#39FF14"),
        Background = Color3.fromHex("#0A1A0A"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#00FF41"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#7FFF00"),
        Button = Color3.fromHex("#00CC00"),
        Icon = Color3.fromHex("#39FF14"),
        Hover = Color3.fromHex("#32CD32"),
        WindowBackground = Color3.fromHex("#0A1A0A"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#0F2A0F"),
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#CCFFCC"),
        DialogIcon = Color3.fromHex("#00FF41"),
        WindowTopbarButtonIcon = Color3.fromHex("#00FF41"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#98FB98"),
        WindowTopbarIcon = Color3.fromHex("#39FF14"),
        TabBackground = Color3.fromHex("#0F2A0F"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#00FF41"),
        ElementBackground = Color3.fromHex("#143314"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#98FB98"),
        ElementIcon = Color3.fromHex("#00FF41"),
        PopupBackground = Color3.fromHex("#0F2A0F"),
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#CCFFCC"),
        PopupIcon = Color3.fromHex("#00FF41")
    })


    dragonhub:AddTheme({
        Name = "DragonHub (Golden Royal)",
        Accent = Color3.fromHex("#FFD700"),
        Background = Color3.fromHex("#151105"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#FFC107"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#FFE082"),
        Button = Color3.fromHex("#D4AF37"),
        Icon = Color3.fromHex("#FFD700"),
        Hover = Color3.fromHex("#FFCA28"),
        WindowBackground = Color3.fromHex("#151105"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#2A210A"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#FFF8DC"),
        DialogIcon = Color3.fromHex("#FFD700"),
        WindowTopbarButtonIcon = Color3.fromHex("#FFD700"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#FFE082"),
        WindowTopbarIcon = Color3.fromHex("#FFD700"),
        TabBackground = Color3.fromHex("#302408"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#FFD700"),
        ElementBackground = Color3.fromHex("#3A2B09"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#FFE082"),
        ElementIcon = Color3.fromHex("#FFD700"),
        PopupBackground = Color3.fromHex("#2A210A"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#FFF8DC"),
        PopupIcon = Color3.fromHex("#FFD700")
    })

    dragonhub:AddTheme({
        Name = "DragonHub (Pink Sakura)",
        Accent = Color3.fromHex("#FF69B4"),
        Background = Color3.fromHex("#1A0D14"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#FF8FC7"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#FFC1DD"),
        Button = Color3.fromHex("#E91E63"),
        Icon = Color3.fromHex("#FF8FC7"),
        Hover = Color3.fromHex("#FF5FA2"),
        WindowBackground = Color3.fromHex("#1A0D14"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#2A1522"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#FFE4EF"),
        DialogIcon = Color3.fromHex("#FF8FC7"),
        WindowTopbarButtonIcon = Color3.fromHex("#FF8FC7"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#FFC1DD"),
        WindowTopbarIcon = Color3.fromHex("#FF69B4"),
        TabBackground = Color3.fromHex("#341B2B"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#FF8FC7"),
        ElementBackground = Color3.fromHex("#402032"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#FFC1DD"),
        ElementIcon = Color3.fromHex("#FF8FC7"),
        PopupBackground = Color3.fromHex("#2A1522"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#FFE4EF"),
        PopupIcon = Color3.fromHex("#FF8FC7")
    })

    dragonhub:AddTheme({
        Name = "DragonHub (Ice Crystal)",
        Accent = Color3.fromHex("#7DF9FF"),
        Background = Color3.fromHex("#09131A"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#B3F5FF"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#D9FCFF"),
        Button = Color3.fromHex("#4FC3F7"),
        Icon = Color3.fromHex("#7DF9FF"),
        Hover = Color3.fromHex("#80DEEA"),
        WindowBackground = Color3.fromHex("#09131A"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#13222A"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#E8FDFF"),
        DialogIcon = Color3.fromHex("#7DF9FF"),
        WindowTopbarButtonIcon = Color3.fromHex("#7DF9FF"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#D9FCFF"),
        WindowTopbarIcon = Color3.fromHex("#7DF9FF"),
        TabBackground = Color3.fromHex("#19303D"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#7DF9FF"),
        ElementBackground = Color3.fromHex("#1E3948"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#D9FCFF"),
        ElementIcon = Color3.fromHex("#7DF9FF"),
        PopupBackground = Color3.fromHex("#13222A"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#E8FDFF"),
        PopupIcon = Color3.fromHex("#7DF9FF")
    })

    dragonhub:AddTheme({
        Name = "DragonHub (Blood Moon)",
        Accent = Color3.fromHex("#B71C1C"),
        Background = Color3.fromHex("#090909"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#D32F2F"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#FF8A80"),
        Button = Color3.fromHex("#8E0000"),
        Icon = Color3.fromHex("#EF5350"),
        Hover = Color3.fromHex("#E53935"),
        WindowBackground = Color3.fromHex("#090909"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#170909"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#FFDADA"),
        DialogIcon = Color3.fromHex("#EF5350"),
        WindowTopbarButtonIcon = Color3.fromHex("#EF5350"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#FF8A80"),
        WindowTopbarIcon = Color3.fromHex("#B71C1C"),
        TabBackground = Color3.fromHex("#220C0C"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#EF5350"),
        ElementBackground = Color3.fromHex("#2B1010"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#FF8A80"),
        ElementIcon = Color3.fromHex("#EF5350"),
        PopupBackground = Color3.fromHex("#170909"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#FFDADA"),
        PopupIcon = Color3.fromHex("#EF5350")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (Mint Breeze)",
        Accent = Color3.fromHex("#74E8C1"),
        Background = Color3.fromHex("#0D1514"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#A8F5DD"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#C8F7EA"),
        Button = Color3.fromHex("#3BCF9B"),
        Icon = Color3.fromHex("#A8F5DD"),
        Hover = Color3.fromHex("#5BE3B0"),
        WindowBackground = Color3.fromHex("#0D1514"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#162321"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#ECFFF8"),
        DialogIcon = Color3.fromHex("#A8F5DD"),
        WindowTopbarButtonIcon = Color3.fromHex("#A8F5DD"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#C8F7EA"),
        WindowTopbarIcon = Color3.fromHex("#74E8C1"),
        TabBackground = Color3.fromHex("#1B2E2A"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#A8F5DD"),
        ElementBackground = Color3.fromHex("#223833"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#C8F7EA"),
        ElementIcon = Color3.fromHex("#A8F5DD"),
        PopupBackground = Color3.fromHex("#162321"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#ECFFF8"),
        PopupIcon = Color3.fromHex("#A8F5DD")
    })
    
    dragonhub:AddTheme({
        Name = "DragonHub (Rose Quartz)",
        Accent = Color3.fromHex("#F29CB2"),
        Background = Color3.fromHex("#171114"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#F8C3D0"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#F5D8E2"),
        Button = Color3.fromHex("#E67A98"),
        Icon = Color3.fromHex("#F8C3D0"),
        Hover = Color3.fromHex("#F5A9BD"),
        WindowBackground = Color3.fromHex("#171114"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#22191D"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#FFF2F6"),
        DialogIcon = Color3.fromHex("#F8C3D0"),
        WindowTopbarButtonIcon = Color3.fromHex("#F8C3D0"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#F5D8E2"),
        WindowTopbarIcon = Color3.fromHex("#F29CB2"),
        TabBackground = Color3.fromHex("#2A1E24"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#F8C3D0"),
        ElementBackground = Color3.fromHex("#34262D"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#F5D8E2"),
        ElementIcon = Color3.fromHex("#F8C3D0"),
        PopupBackground = Color3.fromHex("#22191D"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#FFF2F6"),
        PopupIcon = Color3.fromHex("#F8C3D0")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (Aurora)",
        Accent = Color3.fromHex("#52F7D4"),
        Background = Color3.fromHex("#0A101A"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#8B7CFF"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#BFEFFF"),
        Button = Color3.fromHex("#3ABFF8"),
        Icon = Color3.fromHex("#7EF9E2"),
        Hover = Color3.fromHex("#66D9FF"),
        WindowBackground = Color3.fromHex("#0A101A"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#131D2C"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#E8FFFF"),
        DialogIcon = Color3.fromHex("#7EF9E2"),
        WindowTopbarButtonIcon = Color3.fromHex("#7EF9E2"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#BFEFFF"),
        WindowTopbarIcon = Color3.fromHex("#52F7D4"),
        TabBackground = Color3.fromHex("#18283D"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#8B7CFF"),
        ElementBackground = Color3.fromHex("#21324A"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#BFEFFF"),
        ElementIcon = Color3.fromHex("#7EF9E2"),
        PopupBackground = Color3.fromHex("#131D2C"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#E8FFFF"),
        PopupIcon = Color3.fromHex("#7EF9E2")
    })
    return {
        "DragonHub (New Year)",
        "DragonHub (Purple Nebula)",
        "DragonHub (Emerald Toxic)",
        "DragonHub (Fire Dragon)",
        "DragonHub (Golden Royal)",
        "DragonHub (Pink Sakura)",
        "DragonHub (Ice Crystal)",
        "DragonHub (Blood Moon)",
        "DragonHub (Dark Sakura)",
        "DragonHub (Lavender Dream)",
        "DragonHub (Mint Breeze)",
        "DragonHub (Rose Quartz)",
        "DragonHub (Aurora)",
        "Dark"
    }
end
