return function(dragonhub)
    dragonhub:AddTheme({
        Name = "DragonHub (New Year)",
        Accent = Color3.fromHex("#33CCFF"),
        Background = Color3.fromHex("#121A2E"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#A0E8FF"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#C0D8F0"),
        Button = Color3.fromHex("#2B8FFF"),
        Icon = Color3.fromHex("#B0E0FF"),
        Hover = Color3.fromHex("#66D9FF"),
        WindowBackground = Color3.fromHex("#121A2E"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#182544"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#E6F9FF"),
        DialogIcon = Color3.fromHex("#B0E0FF"),
        WindowTopbarButtonIcon = Color3.fromHex("#B0E0FF"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#C8EEFF"),
        WindowTopbarIcon = Color3.fromHex("#33CCFF"),
        TabBackground = Color3.fromHex("#1A294A"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#87CEEB"),
        ElementBackground = Color3.fromHex("#1F3155"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#C0D8F0"),
        ElementIcon = Color3.fromHex("#87CEEB"),
        PopupBackground = Color3.fromHex("#182544"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#E6F9FF"),
        PopupIcon = Color3.fromHex("#B0E0FF")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (Fire Dragon)",
        Accent = Color3.fromHex("#FF6A00"),
        Background = Color3.fromHex("#140600"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#FF8C1A"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#FFB366"),
        Button = Color3.fromHex("#CC3300"),
        Icon = Color3.fromHex("#FF7B00"),
        Hover = Color3.fromHex("#FF4500"),
        WindowBackground = Color3.fromHex("#140600"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#241000"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#FFD9B3"),
        DialogIcon = Color3.fromHex("#FF7B00"),
        WindowTopbarButtonIcon = Color3.fromHex("#FF8C1A"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#FFB366"),
        WindowTopbarIcon = Color3.fromHex("#FF6A00"),
        TabBackground = Color3.fromHex("#2B1200"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#FF8C1A"),
        ElementBackground = Color3.fromHex("#331400"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#FFB366"),
        ElementIcon = Color3.fromHex("#FF7B00"),
        PopupBackground = Color3.fromHex("#241000"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#FFD9B3"),
        PopupIcon = Color3.fromHex("#FF7B00")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (BlackRed)",
        Accent = Color3.fromHex("#FF0000"),
        Background = Color3.fromHex("#0A0A0A"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#FF3333"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#FF6666"),
        Button = Color3.fromHex("#CC0000"),
        Icon = Color3.fromHex("#FF4444"),
        Hover = Color3.fromHex("#FF1A1A"),
        WindowBackground = Color3.fromHex("#0A0A0A"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#1A0000"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#FFCCCC"),
        DialogIcon = Color3.fromHex("#FF4444"),
        WindowTopbarButtonIcon = Color3.fromHex("#FF3333"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#FF9999"),
        WindowTopbarIcon = Color3.fromHex("#FF0000"),
        TabBackground = Color3.fromHex("#1A0000"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#FF3333"),
        ElementBackground = Color3.fromHex("#200000"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#FF9999"),
        ElementIcon = Color3.fromHex("#FF3333"),
        PopupBackground = Color3.fromHex("#1A0000"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#FFCCCC"),
        PopupIcon = Color3.fromHex("#FF4444")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (Purple Nebula)",
        Accent = Color3.fromHex("#C26DFF"),
        Background = Color3.fromHex("#0D0619"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#E040FB"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#D896FF"),
        Button = Color3.fromHex("#9C27B0"),
        Icon = Color3.fromHex("#E040FB"),
        Hover = Color3.fromHex("#E040FB"),
        WindowBackground = Color3.fromHex("#0D0619"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#1A0A2E"),
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#E6E6FA"),
        DialogIcon = Color3.fromHex("#E040FB"),
        WindowTopbarButtonIcon = Color3.fromHex("#E040FB"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#D896FF"),
        WindowTopbarIcon = Color3.fromHex("#C26DFF"),
        TabBackground = Color3.fromHex("#16213E"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#BA68C8"),
        ElementBackground = Color3.fromHex("#1E1533"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#D896FF"),
        ElementIcon = Color3.fromHex("#E040FB"),
        PopupBackground = Color3.fromHex("#1A0A2E"),
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#E6E6FA"),
        PopupIcon = Color3.fromHex("#E040FB")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (Emerald Toxic)",
        Accent = Color3.fromHex("#39FF14"),
        Background = Color3.fromHex("#0A1A0A"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#00FF41"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#7FFF00"),
        Button = Color3.fromHex("#00CC00"),
        Icon = Color3.fromHex("#39FF14"),
        Hover = Color3.fromHex("#32CD32"),
        WindowBackground = Color3.fromHex("#0A1A0A"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#0F2A0F"),
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#CCFFCC"),
        DialogIcon = Color3.fromHex("#00FF41"),
        WindowTopbarButtonIcon = Color3.fromHex("#00FF41"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#98FB98"),
        WindowTopbarIcon = Color3.fromHex("#39FF14"),
        TabBackground = Color3.fromHex("#0F2A0F"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#00FF41"),
        ElementBackground = Color3.fromHex("#143314"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#98FB98"),
        ElementIcon = Color3.fromHex("#00FF41"),
        PopupBackground = Color3.fromHex("#0F2A0F"),
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#CCFFCC"),
        PopupIcon = Color3.fromHex("#00FF41")
    })
    dragonhub:AddTheme({
        Name = "DragonHub (Ocean Blue)",
        Accent = Color3.fromHex("#00BFFF"),
        Background = Color3.fromHex("#08111F"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#4FC3F7"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#A5D6F9"),
        Button = Color3.fromHex("#1976D2"),
        Icon = Color3.fromHex("#4FC3F7"),
        Hover = Color3.fromHex("#29B6F6"),
        WindowBackground = Color3.fromHex("#08111F"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#10243E"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#D6F4FF"),
        DialogIcon = Color3.fromHex("#4FC3F7"),
        WindowTopbarButtonIcon = Color3.fromHex("#4FC3F7"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#A5D6F9"),
        WindowTopbarIcon = Color3.fromHex("#00BFFF"),
        TabBackground = Color3.fromHex("#123055"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#4FC3F7"),
        ElementBackground = Color3.fromHex("#163A66"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#A5D6F9"),
        ElementIcon = Color3.fromHex("#4FC3F7"),
        PopupBackground = Color3.fromHex("#10243E"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#D6F4FF"),
        PopupIcon = Color3.fromHex("#4FC3F7")
    })

    dragonhub:AddTheme({
        Name = "DragonHub (Golden Royal)",
        Accent = Color3.fromHex("#FFD700"),
        Background = Color3.fromHex("#151105"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#FFC107"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#FFE082"),
        Button = Color3.fromHex("#D4AF37"),
        Icon = Color3.fromHex("#FFD700"),
        Hover = Color3.fromHex("#FFCA28"),
        WindowBackground = Color3.fromHex("#151105"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#2A210A"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#FFF8DC"),
        DialogIcon = Color3.fromHex("#FFD700"),
        WindowTopbarButtonIcon = Color3.fromHex("#FFD700"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#FFE082"),
        WindowTopbarIcon = Color3.fromHex("#FFD700"),
        TabBackground = Color3.fromHex("#302408"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#FFD700"),
        ElementBackground = Color3.fromHex("#3A2B09"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#FFE082"),
        ElementIcon = Color3.fromHex("#FFD700"),
        PopupBackground = Color3.fromHex("#2A210A"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#FFF8DC"),
        PopupIcon = Color3.fromHex("#FFD700")
    })

    dragonhub:AddTheme({
        Name = "DragonHub (Pink Sakura)",
        Accent = Color3.fromHex("#FF69B4"),
        Background = Color3.fromHex("#1A0D14"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#FF8FC7"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#FFC1DD"),
        Button = Color3.fromHex("#E91E63"),
        Icon = Color3.fromHex("#FF8FC7"),
        Hover = Color3.fromHex("#FF5FA2"),
        WindowBackground = Color3.fromHex("#1A0D14"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#2A1522"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#FFE4EF"),
        DialogIcon = Color3.fromHex("#FF8FC7"),
        WindowTopbarButtonIcon = Color3.fromHex("#FF8FC7"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#FFC1DD"),
        WindowTopbarIcon = Color3.fromHex("#FF69B4"),
        TabBackground = Color3.fromHex("#341B2B"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#FF8FC7"),
        ElementBackground = Color3.fromHex("#402032"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#FFC1DD"),
        ElementIcon = Color3.fromHex("#FF8FC7"),
        PopupBackground = Color3.fromHex("#2A1522"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#FFE4EF"),
        PopupIcon = Color3.fromHex("#FF8FC7")
    })

    dragonhub:AddTheme({
        Name = "DragonHub (Ice Crystal)",
        Accent = Color3.fromHex("#7DF9FF"),
        Background = Color3.fromHex("#09131A"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#B3F5FF"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#D9FCFF"),
        Button = Color3.fromHex("#4FC3F7"),
        Icon = Color3.fromHex("#7DF9FF"),
        Hover = Color3.fromHex("#80DEEA"),
        WindowBackground = Color3.fromHex("#09131A"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#13222A"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#E8FDFF"),
        DialogIcon = Color3.fromHex("#7DF9FF"),
        WindowTopbarButtonIcon = Color3.fromHex("#7DF9FF"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#D9FCFF"),
        WindowTopbarIcon = Color3.fromHex("#7DF9FF"),
        TabBackground = Color3.fromHex("#19303D"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#7DF9FF"),
        ElementBackground = Color3.fromHex("#1E3948"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#D9FCFF"),
        ElementIcon = Color3.fromHex("#7DF9FF"),
        PopupBackground = Color3.fromHex("#13222A"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#E8FDFF"),
        PopupIcon = Color3.fromHex("#7DF9FF")
    })

    dragonhub:AddTheme({
        Name = "DragonHub (Blood Moon)",
        Accent = Color3.fromHex("#B71C1C"),
        Background = Color3.fromHex("#090909"),
        BackgroundTransparency = 0,
        Outline = Color3.fromHex("#D32F2F"),
        Text = Color3.fromHex("#FFFFFF"),
        Placeholder = Color3.fromHex("#FF8A80"),
        Button = Color3.fromHex("#8E0000"),
        Icon = Color3.fromHex("#EF5350"),
        Hover = Color3.fromHex("#E53935"),
        WindowBackground = Color3.fromHex("#090909"),
        WindowShadow = Color3.fromHex("#000000"),
        DialogBackground = Color3.fromHex("#170909"),
        DialogBackgroundTransparency = 0,
        DialogTitle = Color3.fromHex("#FFFFFF"),
        DialogContent = Color3.fromHex("#FFDADA"),
        DialogIcon = Color3.fromHex("#EF5350"),
        WindowTopbarButtonIcon = Color3.fromHex("#EF5350"),
        WindowTopbarTitle = Color3.fromHex("#FFFFFF"),
        WindowTopbarAuthor = Color3.fromHex("#FF8A80"),
        WindowTopbarIcon = Color3.fromHex("#B71C1C"),
        TabBackground = Color3.fromHex("#220C0C"),
        TabTitle = Color3.fromHex("#FFFFFF"),
        TabIcon = Color3.fromHex("#EF5350"),
        ElementBackground = Color3.fromHex("#2B1010"),
        ElementTitle = Color3.fromHex("#FFFFFF"),
        ElementDesc = Color3.fromHex("#FF8A80"),
        ElementIcon = Color3.fromHex("#EF5350"),
        PopupBackground = Color3.fromHex("#170909"),
        PopupBackgroundTransparency = 0,
        PopupTitle = Color3.fromHex("#FFFFFF"),
        PopupContent = Color3.fromHex("#FFDADA"),
        PopupIcon = Color3.fromHex("#EF5350")
    })
    return {
        "DragonHub (New Year)",
        "DragonHub (BlackRed)",
        "DragonHub (Purple Nebula)",
        "DragonHub (Emerald Toxic)",
        "DragonHub (Fire Dragon)",
        "DragonHub (Ocean Blue)",
        "DragonHub (Golden Royal)",
        "DragonHub (Pink Sakura)",
        "DragonHub (Ice Crystal)",
        "DragonHub (Blood Moon)",
        "Dark"
    }
end
